import assert from 'node:assert/strict';
import {alignmentSelection,applyAlignment} from '../lib/correction-alignment';
import {transcriptBlocks,replaceTimedText} from '../lib/transcript-structure';
import {useEditorStore as store} from '../lib/store';
import {projectPayload} from '../lib/autosave';
import type {Word} from '../lib/types';
const source:Word[]=Array.from({length:5},(_,id)=>({id,text:'word'+id,start:id,end:id+.9,speaker:id%2,deleted:false,language:'en'}));
const words=replaceTimedText(source,[1,2],'corrected text here',transcriptBlocks(source,[],[],5));
const ids=words.slice(1,4).map(word=>word.id),blocks=transcriptBlocks(words,[],[],5);
const selected=alignmentSelection(words,ids,blocks),before=JSON.stringify(words);
const result=selected.words.map((word,i)=>({...word,start:1.05+i*.5,end:1.45+i*.5,speaker:99,deleted:true}));
const aligned=applyAlignment(words,selected,result,blocks);
assert.equal(JSON.stringify(words),before);assert.equal(aligned[0],words[0]);assert.equal(aligned.at(-1),words.at(-1));
for(const word of aligned.slice(1,4)){assert.equal(word.correction?.timing,'aligned');assert.equal(word.correction?.originalText,'word1 word2');assert.deepEqual(word.correction?.sourceWordIds,[1,2]);assert.equal(word.speaker,-1);assert.equal(word.deleted,false);}
assert.throws(()=>applyAlignment(words,selected,result.slice(1),blocks),/every selected/);
assert.throws(()=>applyAlignment(words,selected,result.map((word,i)=>({...word,start:i?1:NaN})),blocks),/invalid/);
assert.throws(()=>applyAlignment(words,selected,result.map(word=>({...word,id:99})),blocks),/invalid/);
assert.throws(()=>applyAlignment(words,selected,result.map(word=>({...word,text:'different'})),blocks),/invalid/);
assert.throws(()=>applyAlignment(words,selected,result.map(word=>({...word,end:9})),blocks),/invalid/);
const changed=words.map(word=>word.id===ids[0]?{...word,text:'changed'}:word);
assert.throws(()=>applyAlignment(changed,selected,result,transcriptBlocks(changed,[],[],5)),/changed/);
assert.throws(()=>alignmentSelection(words,ids,transcriptBlocks(words,[{start:1.3,end:1.6}],[],5)),/retained/);
assert.throws(()=>alignmentSelection(words,[0,3],blocks),/consecutive/);
store.setState({words,manualCuts:[],sceneBoundaries:[],phrases:[{id:'phrase',wordIds:ids}],clipNames:[],duration:5,past:[],future:[],selectedWordIds:ids,selectionAnchor:ids[0]});
store.getState().applyWordAlignment(selected,result);assert.deepEqual(store.getState().words,aligned);assert.deepEqual(store.getState().phrases,[{id:'phrase',wordIds:ids}]);
assert.equal(store.getState().past.length,1);store.getState().undo();assert.deepEqual(store.getState().words,words);store.getState().redo();assert.deepEqual(store.getState().words,aligned);
store.setState({videoFile:new File([],'alignment.wav'),mediaKind:'audio',skipTranscription:true});
assert.deepEqual(projectPayload()?.words,aligned);store.setState({videoFile:null});
console.log('Selected alignment: strict identity/timing validation, stale rejection, preserved provenance/phrases, atomic undo and autosave payload passed.');
