import {promises as fs} from 'node:fs';
import path from 'node:path';
import {randomUUID} from 'node:crypto';
import {atomicJson,ProjectFiles} from './project-files';
import {ANALYSIS_RATE,ANALYSIS_FRAME,ANALYSIS_CHUNK_SECONDS,type AcousticAnalysis} from '../lib/silence-analysis';
import type {SilenceJob,SilenceChunk} from '../types/silence-api';
const SAMPLES=ANALYSIS_RATE*ANALYSIS_CHUNK_SECONDS;
export class SilenceJobs {
 private tail:Promise<unknown>=Promise.resolve();
 constructor(private projects:ProjectFiles){}
 private serial<T>(fn:()=>Promise<T>){const task=this.tail.catch(()=>{}).then(fn);this.tail=task;return task;}
 private async cache(id:string){return (await this.projects.fileFor(id))+'.cache';}
 private async location(id:string){return path.join(await this.cache(id),'silence');}
 private async audio(id:string){const doc=await this.projects.read(id),cache=await this.cache(id);const info=JSON.parse(await fs.readFile(path.join(cache,'audio.json'),'utf8'));if(info.fingerprint!==doc.media.fingerprint||(await fs.stat(path.join(cache,'audio.f32'))).size!==info.sampleCount*4)throw Error('Prepare source audio before detecting silence.');return {fingerprint:info.fingerprint as string,sampleCount:info.sampleCount as number};}
 async read(id:string):Promise<SilenceJob|null>{try{const job=JSON.parse(await fs.readFile(path.join(await this.location(id),'job.json'),'utf8')) as SilenceJob;return job.fingerprint===(await this.audio(id)).fingerprint?job:null;}catch(error){if((error as NodeJS.ErrnoException).code==='ENOENT')return null;throw error;}}
 private async save(id:string,job:SilenceJob){await atomicJson(path.join(await this.location(id),'job.json'),job);return job;}
 start(id:string){return this.serial(async()=>{const audio=await this.audio(id);if(!Number.isSafeInteger(audio.sampleCount)||audio.sampleCount<=0)throw Error('No prepared audio is available.');const previous=await this.read(id);
 if(previous){const valid:number[]=[];for(const index of previous.completed){try{const row=JSON.parse(await fs.readFile(path.join(await this.location(id),previous.key,index+'.json'),'utf8'));const count=Math.ceil(Math.min(SAMPLES,previous.sampleCount-index*SAMPLES)/ANALYSIS_FRAME);if(Array.isArray(row.rms)&&Array.isArray(row.speech)&&row.rms.length===count&&row.speech.length===count)valid.push(index);}catch{/* Recompute a damaged batch. */}}previous.completed=valid;if(valid.length===previous.total){previous.status='complete';return this.save(id,previous);}}const job:SilenceJob=previous??{...audio,key:randomUUID(),total:Math.ceil(audio.sampleCount/SAMPLES),completed:[],status:'running',message:'Detecting silence',progress:0};job.status='running';job.message='Detecting silence';return this.save(id,job);});}
 pause(id:string){return this.serial(async()=>{const job=await this.read(id);if(job&&job.status!=='complete'){job.status='paused';job.message='Silence detection paused';await this.save(id,job);}});}
 fail(id:string,message:string){return this.serial(async()=>{const job=await this.read(id);if(job){job.status='error';job.message=message;await this.save(id,job);}});}
 async next(id:string):Promise<SilenceChunk|null>{const job=await this.read(id);if(!job||job.status!=='running')return null;const index=Array.from({length:job.total},(_,i)=>i).find(i=>!job.completed.includes(i));if(index===undefined)return null;const core=index*SAMPLES;const start=Math.max(0,core-ANALYSIS_FRAME*64);const count=Math.min(job.sampleCount,(index+1)*SAMPLES)-start;const buffer=Buffer.alloc(count*4);const file=await fs.open(path.join(await this.cache(id),'audio.f32'),'r');try{let offset=0;while(offset<buffer.length){const {bytesRead}=await file.read(buffer,offset,buffer.length-offset,start*4+offset);if(!bytesRead)throw Error('Incomplete prepared audio.');offset+=bytesRead;}}finally{await file.close();}return {index,audio:new Float32Array(buffer.buffer.slice(buffer.byteOffset,buffer.byteOffset+buffer.length)),discardFrames:(core-start)/ANALYSIS_FRAME};}
 checkpoint(id:string,index:number,rms:number[],speech:number[]){return this.serial(async()=>{const job=await this.read(id);if(!job||job.status!=='running'||!Number.isInteger(index)||index<0||index>=job.total)throw Error('Invalid silence checkpoint.');const count=Math.ceil(Math.min(SAMPLES,job.sampleCount-index*SAMPLES)/ANALYSIS_FRAME);if(rms.length!==count||speech.length!==count||rms.some(v=>!Number.isFinite(v)||v<0)||speech.some(v=>!Number.isFinite(v)||v<0||v>1))throw Error('Invalid acoustic analysis.');await atomicJson(path.join(await this.location(id),job.key,index+'.json'),{rms,speech});job.completed=[...new Set([...job.completed,index])].sort((a,b)=>a-b);job.progress=job.completed.length/job.total;if(job.completed.length===job.total){job.status='complete';job.message='Silence detection complete';}await this.save(id,job);return job;});}
 async result(id:string):Promise<AcousticAnalysis|null>{const job=await this.read(id);if(job?.status!=='complete')return null;const rms:number[]=[],speech:number[]=[];for(let i=0;i<job.total;i++){const row=JSON.parse(await fs.readFile(path.join(await this.location(id),job.key,i+'.json'),'utf8'));rms.push(...row.rms);speech.push(...row.speech);}return {version:1,fingerprint:job.fingerprint,duration:job.sampleCount/ANALYSIS_RATE,frameSeconds:ANALYSIS_FRAME/ANALYSIS_RATE,rms,speech};}
}
